name: Build and Push Docker Image

on:
  push:
    paths:
      - 'website/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login with Managed Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.USER_ASSIGNED_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ACR Login with Azure CLI
        run: |
          az acr login --name mdcdemoacr01

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t mdcdemoacr01.azurecr.io/newssite:${IMAGE_TAG} ./website
          docker push mdcdemoacr01.azurecr.io/newssite:${IMAGE_TAG}
          docker tag mdcdemoacr01.azurecr.io/newssite:${IMAGE_TAG} mdcdemoacr01.azurecr.io/newssite:latest
          docker push mdcdemoacr01.azurecr.io/newssite:latest